### PR TITLE
Fixing merge errors qucikfix28.0

### PR DESCRIPTION
**Pull request by Aaditya-Tiwari**
Merging

### CODE REVIEW

**Review by hraetz — APPROVED** [review]
LGTM!

**Review by kevinniu79 — APPROVED** [review]
LGTM!

**Review by NoahRen25 — APPROVED** [review]
LGTM <:)

**Review by jdong03 — APPROVED** [review]
Looks good

**Review by Techbit119 — APPROVED** [review]
good

**Pull request merged**
